<?php

return [
    'opcoes' => [
        'Ensino Técnico',
        'Ensino Fundamental - Anos Iniciais',
        'Ensino Fundamental - Anos Finais',
        'Educação Infantil',
        'Educação Infantil ao 3º Ano do Ensino Fundamental',
        '4º ao 6º ano do Ensino Fundamental',
        '7º ao 9º anos do Ensino Fundamental',
        'Ensino Médio',
        '1º e 2º ano do Ensino Fundamental',
        '3º e 4º ano do Ensino Fundamental',
        'A partir do 5º ano do Ensino Fundamental',
        'Educação Infantil e Ensino Fundamental - Anos iniciais e Finais',
        'CRECHE',
        'PRÉ I - LIVRO 1',
        'PRÉ I - LIVRO 2',
        'PRÉ II - LIVRO 1',
        'PRÉ II - LIVRO 2',
        '1º ANO - Livro 1',
        '1º ANO - Livro 2',
        '2º ANO - Livro 1',
        '2º ANO - Livro 2',
        '3º ANO - Livro 1',
        '3º ANO - Livro 2',
        '4º ANO - Livro 1',
        '4º ANO - Livro 2',
        '5º ANO - Livro 1',
        '5º ANO - Livro 2',
        '6º AO 9º ANO - Livro 1',
        '6º AO 9º ANO - Livro 2',
        'Professores Livro 1',
        'Professores Livro 2',
        'FAMÍLIA I',
        'FAMÍLIA II',
        '4º ao 9º Ano - Ensino Fundamental',
        'Fundamental Anos Finais (6º ao 9º ano) e EJA',
        '1º ano Ensino Fundamental',
        '2º ano Ensino Fundamental',
        '3º ano Ensino Fundamental',
        '4º ano Ensino Fundamental',
        '5º ano Ensino Fundamental',
        '6º ano Ensino Fundamental',
        '7º ano Ensino Fundamental',
        '8º ano Ensino Fundamental',
        '9º ano Ensino Fundamental',
        'Ensino Fundamental - Anos Iniciais 1º ano',
        'Ensino Fundamental - Anos Iniciais 2º ano',
        'Ensino Fundamental - Anos Iniciais 3º ano',
        'Ensino Fundamental - Anos Iniciais 4º ano',
        'Ensino Fundamental - Anos Iniciais 5º ano',
        'Educação Infantil (4 anos)',
        'Educação Infantil - Manual do Professor',
        'Educação Infantil (5 anos)',
        '1º ano - Ensino Fundamental(6 anos)',
        '2º ano - Ensino Fundamental (7 anos)',
        '2º ano - Manual do Professor',
        '3º ano - Ensino Fundamental (8 anos)',
        '3º ano - Manual do Professor',
        '4º ano - Ensino Fundamental (9 anos)',
        '4º ano - Manual do Professor',
        '5º ano - Ensino Fundamental  (10 anos)',
        '5º ano - Manual do Professor',
        'Ensino Fundamental 1º Ano - ',
        'Ensino Fundamental 2º Ano - ',
        'Ensino Fundamental 3º Ano - ',
        'Ensino Fundamental 4º Ano - ',
        'Ensino Fundamental 5º Ano - ',
        'Ensino Fundamental 6º Ano - ',
        'Ensino Fundamental 7º Ano - ',
        'Ensino Fundamental 8º Ano - ',
        'Ensino Fundamental 9º Ano - ',
    ],
];
